# Generated by Django 3.2.15 on 2023-09-09 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='favourited_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_favourited', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='who_favourited',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_favourited', to=settings.AUTH_USER_MODEL),
        ),
    ]
