# Generated by Django 3.2.15 on 2023-09-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230915_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ('id',), 'verbose_name': 'Favourite', 'verbose_name_plural': 'Favourites'},
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('who_favourited', 'favourited_recipe'), name='unique_favourites'),
        ),
    ]
