# Generated by Django 3.2.15 on 2023-09-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20230916_1050'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourite',
            name='unique_favourites',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='favourited_recipe',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='who_favourited',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favourites'),
        ),
    ]
