# Generated by Django 3.2.15 on 2023-09-21 19:28

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_favourite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='in minutes', validators=[django.core.validators.MinValueValidator(1, message='Minimal cooking time is 1!'), django.core.validators.MaxValueValidator(43200, message='Maximal cooking time is 43200')], verbose_name='Cooking Time'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Color (Hex-Code)'),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_name_measurement'),
        ),
    ]
