# Generated by Django 3.2.15 on 2023-09-26 13:09

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230926_1128'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='check_user_not_subscribe_to_self',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('author')), _negated=True), name='check_user_not_subscribe_to_self'),
        ),
    ]
